### PR TITLE
fix novmov and test_streams

### PR DESCRIPTION
**Pull request by tknorris**
ok, one more time.

fix novamov's regex as it wasn't returning the host

and fix test_stream some more...reason has to be cast to a str and it's clearer if those two exceptions don't use 404 as it makes it look like a page not found when it isn't.

### CODE REVIEW

**Comment by tknorris** [comment]
Added in a fix for movreel. Note the old resolver had a bunch of login code present, but the cookies weren't actually loaded in get_media_url so it was useless. I stripped it out.

**Comment by Eldorados** [comment]
I think from pulling in autoloader it conflicted with this guy so I can no longer merge, can you rebase on current master?

**Comment by tknorris** [comment]
yep, will do

**Comment by tknorris** [comment]
done. I also added in the removal of streamcloud resolver. I did some further research and they've been offline for over a year.

**Pull request merged**
