### PR TITLE
Wrapper for t0mm0.common.net with Cloudflare "I'm Under Attack" support

### PR DESCRIPTION
**Pull request by smokdpi**
### Usage:

**Instead of:**
        from t0mm0.common.addon.net import Net
**Use:**
        from lib.cloudflare import CFNet as Net

Then use your instance of Net() the same was as always
        - Cloudflare "I'm Under Attack" will automatically be handled

Also a new function to pass headers/cookies with images/stream_urls or any url

**url_with_headers(url)**
Return URL with headers appended for Kodi
For plugins to return urls for content to kodi that is potentially protected by
Referer/User Agent/Session or Cloudflare cookies.
if url does NOT start with 'http' will just return url

**Example:**
stream_url = 'http://example.com/myvideo.mp4'
stream_url = self.net.url_with_headers(stream_url)
return stream_url
* http://example.com/myvideo.mp4|Referer=%%%%%&User-Agent=%%%%%&Cookie=%%%%%

### CODE REVIEW

**Comment by smokdpi** [comment]
NowVideo removed from this branch and added to a new one for a separate pull request.

**Comment by smokdpi** [comment]
Easiest tests:
choose a resolver you can easily test against
replace the net imports as above
at the top of     get_media_url()

testurl = 'http://kissa***e.com/' #replace the stars of course
print self.net.http_GET(testurl).content
print self.net.url_with_headers(testurl)

you can see the actual page content returned and the cf_clearance cookies and everything being passed in the url.

**Comment by tknorris** [comment]
Let me know when you are sure this ready and I'll add it ot the next TVA release of SMU

**Comment by smokdpi** [comment]
I've continued reviewing, and haven't been able to find anything else that needs fixing. I use a full replacement myself so this was a re-code from that. the main difference was me having cookies saved/loaded within the module without interaction which is why the cookiejar swap issue got through.

From all the review/tests I've done now, it should be good to go now. =)

**Comment by tknorris** [comment]
Are there any hosts that are currently using CF that this can be tested on?

**Comment by smokdpi** [comment]
None that I can say for sure, I think videomega has done it a few times in the past. which is why i provided the test case above to know it works at least. any that do use IUA likely don't always have it on so I had to use sites that are always behind IUA for testing. More a 'future-proofing' lib at this point I think. You can test it on any resolver as a replacement to t0mm0.net import under normal use and to test adding the headers to url though.

**Comment by Eldorados** [comment]
I'm wondering if instead this should be implemented into t0mm0/addon.common rather than urlresolver? 

My view is that urlresolver should be a bit dumb to net communication routines, and this looks like something that might be handy for dev's to have outside of urlresolver

**Comment by tknorris** [comment]
Sounds good to me. I'll hold off on adding it to the TVA release then.

**Comment by smokdpi** [comment]
That would be optimal, should I merge it back to a full net module version? or this wrapper good as is for the addition? and dio you need another pull request, if so which repo?

**Comment by smokdpi** [comment]
I put together 4 versions,
cloudflare(not in...) = this variation
cloudflare(in...) = varitaion that should work from within t0mm0/addon
addon-net/t0mm0-net = as part of each module

https://www.dropbox.com/s/m4xdn5epndeeyax/Cloudflare-Net-Module-Variations.zip?dl=0

**Comment by tknorris** [comment]
My thinking is that the design that would make the most sense would be to instantiate Net() with either CF support turned on or off (default = off to keep it the same as today) and then the rest would be transparent. Do you agree w/ that Eldorado?

**Comment by Eldorados** [comment]
I haven't looked too closely at the code yet, but I was thinking having it optional on the  http_GET and POST calls, would make coding for devs a bit easier where they can just flip a parm as needed, but if it doesn't fit then yeah at least a param on Net init‎@smokdpi, the t0mm0.common addon is in my git repo as well                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: tknorrisSent: Wednesday, September 16, 2015 6:05 PMTo: Eldorados/script.module.urlresolverReply To: Eldorados/script.module.urlresolverCc: EldoradosSubject: Re: [script.module.urlresolver] Wrapper for t0mm0.common.net with Cloudflare "I'm Under Attack" support (#326)My thinking is that the design that would make the most sense would be to instantiate Net() with either CF support turned on or off (default = off to keep it the same as today) and then the rest would be transparent. Do you agree w/ that Eldorado?

—Reply to this email directly or view it on GitHub.

**Comment by tknorris** [comment]
Either way would work for me too.

**Comment by smokdpi** [comment]
i will make the pull requests there with the options at init/post/get, just have to do some tests with it now

**Comment by smokdpi** [comment]
Closing this one, pull requests made to other modules.

**Pull request closed without merging**
