### PR TITLE
Added vkpass.com

### PR DESCRIPTION
**Pull request by seberoth**
Added VKPass-Plugin

### CODE REVIEW

**Comment by tknorris** [comment]
If you can pass along a source of links for this and the stream2k resolver so that I can test them, I'll include these 2 resolvers in the next tva build of urlresolver.

**Comment by seberoth** [comment]
Both link types can be found on a side called seriesever.net . I don't want to share links in public directly because of the copyright.
You can get the links if you select a serie (e.g. 2 Broke Girls), a season and then an episode an you are looking for xhr request to "get_video_part" in your browsers developer console.

**Comment by tknorris** [comment]
got it, I'll check them out

**Comment by tknorris** [comment]
Tested and added. I made some small changes to make them look/work more consistently with other resolvers. I'll include them in the next tva bulid.

**Comment by seberoth** [comment]
Thanks, i know the code isn't the best. I started coding with Python last sunday :)

**Comment by tknorris** [comment]
The code looked fine to me. The vk.com resolver is just old so some of the ways it does things have been changed over time. The more contributors the better!

**Comment by tknorris** [comment]
FYI, this and stream2k resolver were pushed in the 2.9.9 tva build of urlresolver.

**Comment by Eldorados** [comment]
Added in #314

**Pull request closed without merging**
