### PR TITLE
Update youtube.py

### PR DESCRIPTION
**Pull request by mikey1234**
change youtube plugin to use the yt module

### CODE REVIEW

**Comment by tknorris** [comment]
I hate the idea of making everyone use a hacked resolver rather than the real youtube addon just to support Gotham users that are 2 stable releases behind already...

**Comment by Eldorados** [comment]
Yeah I agree here

A couple possible solutions:
- drop dependency - is youtube still installed by default on fresh Kodi installs?
- move dependency to an optional include - I believe this can be done (?)

Otherwise users so far behind should be upgrading

**Comment by tknorris** [comment]
*Technically* there is no dependency on youtube. The resolver use plugin:// urls which will work if youtube is installed (and not if it's not obviously) regardless of whether the dependency is in addon.xml

**Comment by mikey1234** [comment]
Dependency does not need to be there

There is thousands of users still on frodo and Gotham 

Issue with Gotham though is if an addon depends on urlresolver the addon won't even install because no YouTube 


Thanks

Mikes iphone

**Comment by Eldorados** [comment]
Fixed in #328 by removing youtube dependency

**Pull request closed without merging**
