### PR TITLE
vidgg, openload.co fix, watchvideo new resolver, minor correction in youtube resolver

### PR DESCRIPTION
**Pull request by Gujal00**
youtube resolver modified to use youtube v5 style calls.
vidgg modified to use new format
watchvideo new resolver
openload.co fix using new browser method instead of api call
playhd, speedplay and mersalaayitten new resolvers

### CODE REVIEW

**Comment by tknorris** [comment]
I'll merge these into my repo, but we should change openload to fall back to the API if the url can't be found w/ the AAdecode

**Comment by tknorris** [comment]
I've added the changes in this PR into PR #365 They will be in the next TVA release. (Note I updated openload to fall back ot the API if the decoder attempt fails for any reason)

**Comment by Gujal00** [comment]
Thanks mate. Was thinking the same after I did the pull request. good that you includedthe fallback option with the API.

**Comment by Gujal00** [comment]
Great that you have included all my suggested changes. Will close this request

**Pull request closed without merging**
