### PR TITLE
Hugefiles Fix

### PR DESCRIPTION
**Pull request by tknorris**
This fixes the hugefiles resolver. They started doing the no protocol address for solvemedia and it broke the resolver.

I'm considering adding some code in to push the url detection down into the captcha_lib so that if other hosters do this we can fix it in one place.

### CODE REVIEW

**Comment by s7eele** [comment]
👍

**Comment by tknorris** [comment]
That 2nd commit is the captcha improvement. I tested 180upload, hugefiles, and vidplay. It might be good to test vidxden but I couldn't find any links to test with.

**Comment by s7eele** [comment]
i know im running way behind hut i played a couple vidxden

**Comment by tknorris** [comment]
You have to wait for this code to be merged, then either run your own dev verson pulled from github of Eldorado's urlresolver repo or, let Eldorado push a beta out via his beta repo. 

The existing resolver works fine, but I did some centralized improvements to the captcha library that impacted that code and (possibly) broke it.

**Comment by s7eele** [comment]
damnit, i knew that, im not focused, thinking in too many directions, however id appeciate your input tknorris:

im running his beta repo (core module beta repo) but im trying to do what you describe by pulling dev version from github, isnt that basically the same thing i was doing as you guys worked trakt add-on upgrade(with your support)? especially while i was working on the playlist-sync branch before it was merged? im thinking the seperate branch probably made it a bit easier but shouldnt i be able to test changes (made via pr or whatever) before they are merged by making sure ive got the right files/etc, oversimplified a LOT but am i thinking correctly?

im asking because thats basically what id like to try here (and other places), all in an effort to better understand things, ultimate goal would be actually contributing to the code but ive got lots to learn still

**Comment by tknorris** [comment]
You can't really pull down a change that hasn't been merged yet like that. If you really want to try to do that then you have to go to the source repository that has the PR pending and download the zip from there. For instance in this case, you can download the zip from my github fork on urlresolver and it will include this change.

TBH though, you are better off just waiting for Eldorado to merge it. It's not a big deal if we break a beta version of urlresolver...That's why we have betas, so we can break them.

**Comment by s7eele** [comment]
what you describe is exactly what i meant and what ive been doing lol

im not doing it just to try to have the latest or just to beta test in every case, it really helps me learn and its really the only way ill ever contribute to code on github, correct?

i havent cloned many repositories and tbh trakt is rhe only one ive had a chance to do anything with but om gonna keep trying, like i said i was just making sure i wasnt completely off track, i think i get the basics lol

i appreciate your patience and help, if you ever need a break from it let me know, ill try tokeep it to a minimum, peace

**Comment by tknorris** [comment]
The way to contribute code is via Pull Requests. So, have you fork the repo on github, then clone it locally, then commit and push/pull from that fork. When I first started working with git I read this documentation to understand the different concepts: http://git-scm.com/doc

**Comment by s7eele** [comment]
thx friend, ive done a couple pull requests for on trakt upgrade and im giving sourcetree a try as a 'client', pretty sure ive got the basics down wrt to cloning a repo, making changes locally, testing and submitting pr but im sure ill have questions, will read suggested documentation, found the wiki to be a little disconnected, not super helpful

so hopefully ill be able to try out changes others make before they are merged, got quite comfortable doing it through work with trakt upgrade, ill stay out of the way, learning experience :-)

**Comment by s7eele** [comment]
hey @tknorris, ive been asking around about peoples preferences re: git/github (among many other things), it seems to me a client of some type is a good idea if not necessary, i mentioned i was going to check out sourcetree and ive looked into github windows client (w/ included command line interface), ive also looked at some android clientss like github and pocketgit and octodroid, just for keeping in touch while on the go ive been using octodroid, on the windows side (no linux atm) im not sure if absolutely everything can be done via browser or windows github client w/ cli but it seems clients like sourcetree certainly make things easier, i would appreciate hearing your thoughts on the matter when u have a moment?

**Comment by tknorris** [comment]
I use just a browser on my desktop. I use the github app on Android, but it's doesn't work very well. I can't get it to show issues at all. As far as managing git and github repos, I use Eclipse's git plugin. It's probably not the best git client, but having it integrated w/ my IDE is nice.

**Comment by s7eele** [comment]
eclipse was the answer to my first question,nabout python octodroid gives u a nice interface to create/comment/close issues, pr, or review activity but dont think it has much to offer in the way of actual code manipulation, might be worth a shot if you havent tried already

**Comment by tknorris** [comment]
I'll take a look at it. It would be nice to have a github android app that actually works.

**Comment by Eldorados** [comment]
Hey guys, can you move this convo off the pull request? Forums or email?Thanks!                                                                                                                                                                                                                                                                          Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                                         From: s7eeleSent: Saturday, March 14, 2015 1:28 AMTo: Eldorados/script.module.urlresolverReply To: Eldorados/script.module.urlresolverSubject: Re: [script.module.urlresolver] Hugefiles Fix (#276)eclipse was the answer to my first question,nabout python octodroid gives u a nice interface to create/comment/close issues, pr, or review activity but dont think it has much to offer in the way of actual code manipulation, might be worth a shot if you havent tried already

—Reply to this email directly or view it on GitHub.

**Comment by s7eele** [comment]
my bad, apologies, ill delete this comment as well, after youve had an opportunity to see it, no reply necessary

**Pull request merged**
