### PR TITLE
Autoloader 3

### PR DESCRIPTION
**Pull request by VioletRed**
Cleaner pull request replacing #232. Only 4 commits, one for each improvement:

1 & 3 - Domain check resolvers before using them  (reduce resolution time).
2- Don't write settings.xml with each initialization of the plugin (reduce initialization time).
4 - Dynamically load resolvers only when used  (reduce initialization time).

### CODE REVIEW

**Comment by Eldorados** [comment]
Hate to do this to ya, but it looks like you may need to re-base first.. I'm not able to merge this one

**Comment by VioletRed** [comment]
Rebase or merge? A rebase would mean creating a new PR, but also would give the chance to put the patches in the order tknorris sugested (first initialization optimization and then resolution ones), if you think it's better.

**Comment by Eldorados** [comment]
I believe you need to rebase, the option for me to auto merge is not available - which usually is a result of your changes being behind what is currently in master

**Comment by tknorris** [comment]
If you include all the commits in one PR, then there is no way to merge them in pieces like we talked about.

**Pull request closed without merging**
