### PR TITLE
Fixed vkpass.com & added ok.ru

### PR DESCRIPTION
**Pull request by seberoth**
Also a small change in the types.py to handle cookies (url encoding doesn't seems to work for some reason)

### CODE REVIEW

**Comment by tknorris** [comment]
Hey, if you urllib.quote() the cookie before including it in the stream url I think it will allow test_stream to remained unchanged. If you that will work and you can update that then I'll add this ot the next tva release of urlresolver.

**Comment by tknorris** [comment]
FYI, I added both of these changes in my latest PR.  Rather than use urllib.quote() I just replaced the = in the cookie with %3D. Kodi will unquote it before it uses it.

**Comment by seberoth** [comment]
Ok thanks. I tested that also but unfortunately it hasn't worked on my end...
maybe I have done something wrong

**Comment by tknorris** [comment]
Hm, it should work. Kodi unquotes the params before it includes them in the header. If you can share a link w/ me I'll test it

**Comment by seberoth** [comment]
Just tested it again. The problem is, that types.py (__test_stream) doesn't unquoute it. So this request will fail and urlresolver thinks the link is broken

**Comment by tknorris** [comment]
got it, I'll add the unquote in to test_stream

**Comment by Eldorados** [comment]
Merged as part of #356

**Pull request closed without merging**
