### PR TITLE
handle openload errors more cleanly

### PR DESCRIPTION
**Pull request by tknorris**

### CODE REVIEW

**Comment by smokdpi** [comment]
openload required an additional update, so I included this error handling. also included fix thevideo.me without the print html in pull #334

**Comment by tknorris** [comment]
Ok, I'll pull those into my repo and push them out in the next TVA release...

**Comment by smokdpi** [comment]
In the future, resolver wise do you guys prefer that I make the pull requests here, or tknorris' fork. Which will make the process smoother for you?

**Comment by tknorris** [comment]
either works for me, if you submit them here, I'll merge them back into mine, if not, then I'll include them in my PR's to Eldorado.

**Pull request merged**
