### PR TITLE
Don't write settings.xml to the install location

### PR DESCRIPTION
**Pull request by edwtjo**
Since that is the reason profiles exists and the install location might
be read only after installation.

### CODE REVIEW

**Comment by tknorris** [comment]
This is the same issue we talked about on the SALTS repository. Writing this to the user profile won't work properly.

**Comment by Eldorados** [comment]
Agreed, there is no issue here that I'm aware of so why the change?

**Comment by tknorris** [comment]
There is an issue on some platforms that the addon location isn't writeable, but writing this to userdata doesn't solve the problem.

**Comment by Eldorados** [comment]
Closing this - this file must be first written to the addon folder as that is where Kodi will look for it

**Pull request closed without merging**
